"""Build the FRD-to-STTM one-slide system-architecture deck (PPTX).

    .venv/bin/pip install python-pptx pillow     # deck-building only, not runtime deps
    .venv/bin/python scripts/build_architecture_onepager.py [output.pptx]

Default output: context/FRD_to_STTM_Agent_System_Architecture.pptx

ONE slide, three bands:
  1. the flow — five nodes left to right (SharePoint → scheduled read-only
     sync → the four-stage Databricks job, whose stage 02 is the only model
     call → human-in-the-loop review → outputs + downstream agents), with
     the gold return loop (the reviewer uploads; the sync pairs it);
  2. four images — the FRD going in (rendered page), two REAL review-app
     screenshots lifted from context/FRD_to_STTM_Agent_Screens.html
     (synthetic corpus — no client content), and the STTM workbook coming
     out (rendered sheet preview built from the synthetic smoke rows);
  3. the doctrine line + a status tag.

Visual system (2026-08-22, v2 after "too crowded" feedback): dark,
data-dense but AIRY — ≈150 words, nothing under 7.5 pt, body ≥ 9 pt. The
palette is Palantir's open-source Blueprint design system
(github.com/palantir/blueprint, packages/colors/_colors.scss): near-black
canvas `111418`, dark-gray cards `1c2127`/`252a31`, hairlines `383e47`, a
gray text ramp, and accent families used as a SEMANTIC code:
    cerulean `3fa6da`  = the LLM (exactly one place)
    turquoise `13c9ba` = deterministic code
    gold `f0b726`      = a human
    indigo `9881f3`    = external systems (SharePoint, downstream agents)
Typography: Calibri (body) + Courier New (mono ids / tracked labels) — both
ship with Office and render true-to-width in LibreOffice QA. Background and
the two document previews are PNGs generated by this script (Pillow, system
fonts) into scripts/deck_assets/onepager_generated/; Lucide icons live in
scripts/deck_assets/icons_dark (react-icons/lu). Everything is
absolute-positioned on a 13.333" × 7.5" canvas.

Every statement on the slide is true of `staging` as of 2026-08-22; the
slide claims no live deployment.
"""
from __future__ import annotations

import base64
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_CONNECTOR, MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.oxml.ns import qn
from pptx.util import Inches, Pt

REPO = Path(__file__).resolve().parent.parent
ASSETS = REPO / "scripts" / "deck_assets"
ICONS = ASSETS / "icons_dark"
GEN = ASSETS / "onepager_generated"
SCREENS_HTML = REPO / "context" / "FRD_to_STTM_Agent_Screens.html"
OUT_DEFAULT = REPO / "context" / "FRD_to_STTM_Agent_System_Architecture.pptx"

# --- Blueprint palette (hex without '#') -----------------------------------
BLACK = "111418"
DG1, DG2, DG3, DG4, DG5 = "1c2127", "252a31", "2f343c", "383e47", "404854"
G1, G2, G3, G4, G5 = "5f6b7c", "738091", "8f99a8", "abb3bf", "c5cbd3"
LG5 = "f6f7f9"
WHITE = "ffffff"
CERULEAN, CERULEAN_DIM = "3fa6da", "0f6894"
TURQ, TURQ_DIM = "13c9ba", "007067"
GOLD, GOLD_DIM = "f0b726", "866103"
INDIGO, INDIGO_DIM = "9881f3", "634dbf"

SANS = "Calibri"
MONO = "Courier New"
W_IN, H_IN = 13.333, 7.5

# PIL fonts (macOS system fonts first; any TTF works — only the previews use them)
_FONT_CANDIDATES = {
    "sans": ["/System/Library/Fonts/Helvetica.ttc", "/Library/Fonts/Arial.ttf",
             "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"],
    "mono": ["/System/Library/Fonts/Menlo.ttc", "/Library/Fonts/Courier New.ttf",
             "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"],
}


def _font(kind: str, size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    for p in _FONT_CANDIDATES[kind]:
        if Path(p).exists():
            try:
                return ImageFont.truetype(p, size, index=1 if (bold and p.endswith(".ttc")) else 0)
            except OSError:
                return ImageFont.truetype(p, size)
    return ImageFont.load_default()


# --------------------------------------------------------------------------- #
# generated images
# --------------------------------------------------------------------------- #
def make_background(path: Path) -> Path:
    w, h = 2560, 1440
    img = Image.new("RGB", (w, h), "#" + BLACK)
    glow = Image.new("RGB", (w, h), "#" + BLACK)
    gd = ImageDraw.Draw(glow)
    gd.ellipse([-400, -500, 1500, 900], fill="#161c24")
    gd.ellipse([1500, 700, 3200, 1900], fill="#141a21")
    glow = glow.filter(ImageFilter.GaussianBlur(260))
    img = Image.blend(img, glow, 0.9)
    d = ImageDraw.Draw(img)
    for y in range(40, h, 40):
        for x in range(40, w, 40):
            d.point((x, y), fill="#262c35")
    img.save(path, optimize=True)
    return path


FRD_LINES = [  # the SYNTHETIC smoke FRD (tools/make_synthetic_smoke_fixture.py)
    ("h", "Functional Requirements Document"),
    ("m", "Project ID: 9100001     Project Name: Synthetic Member Risk Ingestion"),
    ("", ""),
    ("s", "Data Ingestion Requirements"),
    ("p", "The Synthetic Vendor delivers the pipe (|) delimited text file"),
    ("p", "{SYN_MEMBER_RISK_YYYYMMDD.txt} weekly to {/synthetic/landing/synthetic_member_risk}."),
    ("p", "The feed loads the columns MEMBER_ID, ZIP_CODE, RISK_SCORE, EFFECTIVE_DATE,"),
    ("p", "LOB_CODE into the stage table {syn_cat.syn_stg.SYN_MEMBER_RISK} (Truncate and"),
    ("p", "Load) and is promoted to {syn_cat.syn_std.SYN_MEMBER_RISK}."),
    ("", ""),
    ("s", "Data Quality"),
    ("p", "REQ-001  Process shall reject the record when MEMBER_ID is NULL and move"),
    ("p", "it to the reject table."),
]


def make_frd_preview(path: Path) -> Path:
    """A page of the synthetic FRD; strict-grounded spans ({…}) underlined in
    cerulean — the fields 03 must find verbatim."""
    w, h = 1600, 780
    img = Image.new("RGB", (w, h), "#" + DG2)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([60, 40, w - 60, h + 40], radius=18, fill="#f6f7f9")
    fh, fs, fp, fm = _font("sans", 44, True), _font("sans", 30, True), _font("sans", 28), _font("mono", 24)
    y = 90
    for kind, text in FRD_LINES:
        x = 120
        if kind == "h":
            d.text((x, y), text, font=fh, fill="#1c2127"); y += 70
        elif kind == "m":
            d.text((x, y), text, font=fm, fill="#5f6b7c"); y += 56
        elif kind == "s":
            d.text((x, y), text, font=fs, fill="#215db0"); y += 52
        elif kind == "p":
            for part in re.split(r"(\{[^}]+\})", text):
                if not part:
                    continue
                strict = part.startswith("{")
                t = part.strip("{}")
                d.text((x, y), t, font=fp, fill="#1c2127")
                tw = d.textlength(t, font=fp)
                if strict:
                    d.line([x, y + 36, x + tw, y + 36], fill="#" + CERULEAN, width=4)
                x += tw
            y += 44
        else:
            y += 26
    fade = Image.new("L", (w, h), 0)
    fd = ImageDraw.Draw(fade)
    for i in range(140):
        fd.line([0, h - 140 + i, w, h - 140 + i], fill=int(255 * i / 140))
    img = Image.composite(Image.new("RGB", (w, h), "#" + DG2), img, fade)
    img.save(path, optimize=True)
    return path


WB_ROWS = [  # synthetic smoke rows as 04 renders them (sheet MAPPING-SYN_MEMBER_RISK)
    ("MEMBER_ID", "Not NULL", "Process shall reject the record when MEMBER_ID is NULL…", "syn_stg", "SYN_MEMBER_RISK", "MEMBER_ID", "syn_std", "MEMBER_ID"),
    ("ZIP_CODE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "ZIP_CODE", "syn_std", "ZIP_CODE"),
    ("RISK_SCORE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "RISK_SCORE", "syn_std", "RISK_SCORE"),
    ("EFFECTIVE_DATE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "EFFECTIVE_DATE", "syn_std", "EFFECTIVE_DATE"),
    ("LOB_CODE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "LOB_CODE", "syn_std", "LOB_CODE"),
    ("NA", "NULL", "", "syn_stg", "SYN_MEMBER_RISK", "SYN_SRC_FILE", "syn_std", "SYN_SRC_FILE"),
    ("NA", "NULL", "", "syn_stg", "SYN_MEMBER_RISK", "SYN_LOAD_TS", "syn_std", "SYN_LOAD_TS"),
]


def make_workbook_preview(path: Path) -> Path:
    """The rendered STTM sheet as a spreadsheet: band row, header row, rows —
    the Comment cell carries the FRD rule on the row it names."""
    w, h = 1600, 780
    img = Image.new("RGB", (w, h), "#" + DG2)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([60, 40, w + 200, h + 40], radius=18, fill="#ffffff")
    ft = _font("sans", 22)
    tx = 90
    for name, active in (("FILE_DETAILS", False), ("VERSION_HISTORY", False), ("MAPPING-SYN_MEMBER_RISK", True)):
        tw = d.textlength(name, font=ft) + 40
        d.rounded_rectangle([tx, 56, tx + tw, 100], radius=8, fill=("#ffffff" if active else "#e5e8eb"), outline="#c5cbd3")
        d.text((tx + 20, 66), name, font=ft, fill=("#215db0" if active else "#5f6b7c"))
        tx += tw + 8
    cols = [("Database column Name", 250), ("NULL CHECK", 140), ("Comment", 470), ("Schema", 120),
            ("TableName", 230), ("ColumnName", 200), ("Schema", 120), ("ColumnName", 200)]
    x0, y0 = 60, 120
    fb, fhd, fc, fcm = _font("sans", 24, True), _font("sans", 23, True), _font("sans", 23), _font("mono", 21)
    x, ci = x0, 0
    for name, n in (("Source File Layout", 3), ("Stage Layer", 3), ("Standard Layer", 2)):
        bw = sum(cw for _, cw in cols[ci:ci + n])
        d.rectangle([x, y0, x + bw, y0 + 46], fill="#bdd7ee", outline="#ffffff")
        d.text((x + 12, y0 + 9), name, font=fb, fill="#1c2127")
        x += bw
        ci += n
    x = x0
    for name, cw in cols:
        d.rectangle([x, y0 + 46, x + cw, y0 + 92], fill="#d9e1f2", outline="#ffffff")
        d.text((x + 12, y0 + 56), name, font=fhd, fill="#1c2127")
        x += cw
    y = y0 + 92
    for r in WB_ROWS:
        x = x0
        for (name, cw), val in zip(cols, r):
            d.rectangle([x, y, x + cw, y + 48], fill="#ffffff", outline="#edeff2")
            if name == "Comment" and val:
                d.rectangle([x + 1, y + 1, x + cw - 1, y + 47], fill="#e8f4fb")
                d.text((x + 12, y + 12), val, font=fcm, fill="#0f6894")
            else:
                d.text((x + 12, y + 11), val,
                       font=(fcm if name in ("Schema", "TableName", "ColumnName") else fc),
                       fill=("#8f99a8" if val in ("NA", "NULL") else "#1c2127"))
            x += cw
        y += 48
    fade = Image.new("L", (w, h), 0)
    fd = ImageDraw.Draw(fade)
    for i in range(120):
        fd.line([w - 120 + i, 0, w - 120 + i, h], fill=int(255 * i / 120))
    img = Image.composite(Image.new("RGB", (w, h), "#" + DG2), img, fade)
    img.save(path, optimize=True)
    return path


def extract_screens(out_dir: Path) -> dict[str, Path]:
    """Lift the review-app screenshots out of the static walkthrough (base64
    <img>s). Returns {alt: path}; empty if the HTML is absent."""
    if not SCREENS_HTML.exists():
        return {}
    html = SCREENS_HTML.read_text(encoding="utf-8")
    found = {}
    for m in re.finditer(r'<img src="data:image/(\w+);base64,([^"]+)" alt="([^"]+)"', html):
        ext, b64, alt = m.groups()
        p = out_dir / (re.sub(r"[^a-z0-9]+", "_", alt.lower()).strip("_") + "." + ext)
        p.write_bytes(base64.b64decode(b64))
        found[alt] = p
    return found


def crop_to(path: Path, box_frac, out: Path) -> Path:
    im = Image.open(path)
    w, h = im.size
    l, t, r, b = box_frac
    im.crop((int(l * w), int(t * h), int(r * w), int(b * h))).save(out, optimize=True)
    return out


# --------------------------------------------------------------------------- #
# pptx helpers
# --------------------------------------------------------------------------- #
def rgb(h: str) -> RGBColor:
    return RGBColor.from_string(h.upper())


def _no_shadow(shape):
    spPr = shape._element.spPr
    spPr.append(spPr.makeelement(qn("a:effectLst"), {}))


def add_text(slide, x, y, w, h, runs, *, size=10, color=G5, font=SANS, bold=False,
             align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP, spacing=None, line_spacing=None):
    tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    tf.vertical_anchor = anchor
    paragraphs = runs
    if isinstance(runs, str):
        paragraphs = [[(runs, {})]]
    elif runs and not isinstance(runs[0], list):
        paragraphs = [runs]
    for pi, para in enumerate(paragraphs):
        p = tf.paragraphs[0] if pi == 0 else tf.add_paragraph()
        p.alignment = align
        if line_spacing:
            p.line_spacing = line_spacing
        for text, ov in para:
            r = p.add_run()
            r.text = text
            f = r.font
            f.name = ov.get("font", font)
            f.size = Pt(ov.get("size", size))
            f.bold = ov.get("bold", bold)
            f.color.rgb = rgb(ov.get("color", color))
            sp = ov.get("spacing", spacing)
            if sp is not None:
                r._r.get_or_add_rPr().set("spc", str(int(sp * 100)))
    return tb


def add_rect(slide, x, y, w, h, *, fill=DG1, line=DG4, line_w=0.75, radius=None):
    kind = MSO_SHAPE.ROUNDED_RECTANGLE if radius is not None else MSO_SHAPE.RECTANGLE
    s = slide.shapes.add_shape(kind, Inches(x), Inches(y), Inches(w), Inches(h))
    if radius is not None:
        s.adjustments[0] = radius
    if fill is None:
        s.fill.background()
    else:
        s.fill.solid()
        s.fill.fore_color.rgb = rgb(fill)
    if line is None:
        s.line.fill.background()
    else:
        s.line.color.rgb = rgb(line)
        s.line.width = Pt(line_w)
    _no_shadow(s)
    s.text_frame.text = ""
    return s


def add_line(slide, x1, y1, x2, y2, *, color=G1, width=0.75, head=False, dash=None):
    c = slide.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(x1), Inches(y1), Inches(x2), Inches(y2))
    c.line.color.rgb = rgb(color)
    c.line.width = Pt(width)
    ln = c.line._get_or_add_ln()
    if dash:
        ln.append(ln.makeelement(qn("a:prstDash"), {"val": dash}))
    if head:
        ln.append(ln.makeelement(qn("a:tailEnd"), {"type": "triangle", "w": "sm", "len": "sm"}))
    return c


def add_dot(slide, cx, cy, d, color):
    s = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(cx - d / 2), Inches(cy - d / 2), Inches(d), Inches(d))
    s.fill.solid()
    s.fill.fore_color.rgb = rgb(color)
    s.line.fill.background()
    _no_shadow(s)
    return s


def add_icon(slide, name, x, y, size):
    p = ICONS / f"{name}.png"
    if p.exists():
        slide.shapes.add_picture(str(p), Inches(x), Inches(y), Inches(size), Inches(size))


def add_image(slide, path, x, y, w, h):
    """Place an image scaled to FIT inside (w, h), centered — never distorted."""
    iw, ih = Image.open(path).size
    scale = min(w / iw, h / ih)
    pw, ph = iw * scale, ih * scale
    slide.shapes.add_picture(str(path), Inches(x + (w - pw) / 2), Inches(y + (h - ph) / 2), Inches(pw), Inches(ph))


def label(slide, x, y, w, text, *, color=G3, size=8, align=PP_ALIGN.LEFT):
    return add_text(slide, x, y, w, 0.22, [(text.upper(), {})], size=size, color=color, font=MONO,
                    spacing=1.6, align=align)


CHIP_CHAR, CHIP_PAD = 0.083, 0.34   # Courier New 7.5 pt + 1 pt tracking, measured in QA


def chip(slide, x, y, text, *, color=G4, border=DG5, size=7.5):
    w = CHIP_CHAR * len(text) + CHIP_PAD
    add_rect(slide, x, y, w, 0.26, fill=None, line=border, line_w=0.6, radius=0.5)
    add_text(slide, x, y + 0.055, w, 0.18, [(text.upper(), {})], size=size, color=color, font=MONO,
             spacing=1.0, align=PP_ALIGN.CENTER)
    return x + w + 0.1


def crosshair(slide, cx, cy, arm=0.07):
    add_line(slide, cx - arm, cy, cx + arm, cy, color=DG5, width=0.5)
    add_line(slide, cx, cy - arm, cx, cy + arm, color=DG5, width=0.5)


# --------------------------------------------------------------------------- #
# the slide
# --------------------------------------------------------------------------- #
def build(out: Path) -> Path:
    GEN.mkdir(parents=True, exist_ok=True)
    bg = make_background(GEN / "background.png")
    frd_img = make_frd_preview(GEN / "frd_page.png")
    wb_img = make_workbook_preview(GEN / "sttm_sheet.png")
    shots = extract_screens(GEN)
    pick = shots.get("Select FRD — the corpus picker")
    review = shots.get("Results — ambiguity gate and human-in-the-loop review")
    if pick:
        pick = crop_to(pick, (0.15, 0.30, 0.85, 0.99), GEN / "shot_pick.png")
    if review:
        review = crop_to(review, (0.15, 0.05, 0.85, 0.74), GEN / "shot_review.png")
    # the raw extracted screenshots are scratch — keep only what the slide uses
    for p in shots.values():
        p.unlink(missing_ok=True)

    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(W_IN), Inches(H_IN)
    s = prs.slides.add_slide(prs.slide_layouts[6])
    s.shapes.add_picture(str(bg), 0, 0, prs.slide_width, prs.slide_height)
    for cx, cy in ((0.3, 0.3), (W_IN - 0.3, 0.3), (0.3, H_IN - 0.3), (W_IN - 0.3, H_IN - 0.3)):
        crosshair(s, cx, cy)

    # ----- header ------------------------------------------------------------
    label(s, 0.6, 0.42, 9, "Hexaware  ·  AmeriHealth Caritas  ·  AI-in-Engineering  ·  agent 01 / 03", color=G2)
    add_text(s, 0.6, 0.64, 9, 0.55, [("FRD → STTM Agent", {"color": WHITE, "bold": True, "size": 28}),
                                     ("    system architecture", {"color": G3, "size": 15})], size=28)
    add_text(s, 0.6, 1.16, 7.6, 0.3,
             [("An approved requirements document becomes an audited source-to-target mapping — "
               "every fact checked against the source text, every ambiguity routed to a person.", {})],
             size=11, color=G4)
    rows = [(0.7, [("read-only SharePoint", INDIGO, INDIGO_DIM), ("1 model call / document", CERULEAN, CERULEAN_DIM)]),
            (1.04, [("verdicts computed in code", TURQ, TURQ_DIM), ("human in the loop", GOLD, GOLD_DIM)])]
    for yy, row in rows:
        widths = [CHIP_CHAR * len(t) + CHIP_PAD for t, _, _ in row]
        cx = W_IN - 0.6 - sum(widths) - 0.1 * (len(row) - 1)
        for (t, col, bd), w in zip(row, widths):
            cx = chip(s, cx, yy, t, color=col, border=bd)

    # ----- band 1: the flow ----------------------------------------------------
    TOP, NH = 1.85, 1.95
    nodes = [  # x, w, accent, icon, idx, title, caption
        (0.6, 2.05, INDIGO, "folder", "SRC", "SharePoint library",
         "System of record. FRDs in, approved STTMs back. The agent only ever reads it."),
        (3.0, 2.05, TURQ, "refresh", "00", "Scheduled sync",
         "Every 15 min, incremental. Pairs each FRD with its STTM and indexes the corpus in Unity Catalog. Zero model calls."),
        (5.4, 3.15, TURQ, None, "01-04", "Generation job",
         "Four stages on Databricks. Extract is the single Claude call; parse, audit, gate and render are code."),
        (8.9, 2.05, GOLD, "user", "HITL", "Review app",
         "Pick an FRD, run, answer what the agent could not settle, re-render — then upload the approved STTM yourself."),
        (11.3, 1.45, INDIGO, "code", "OUT", "Outputs",
         "STTM workbook + feed contract → CodeGen and Code Review agents."),
    ]
    for x, w, acc, icon, idx, title, cap in nodes:
        add_rect(s, x, TOP, w, NH, fill=DG1, line=DG4, radius=0.04)
        add_dot(s, x + 0.24, TOP + 0.27, 0.1, acc)
        add_text(s, x + 0.4, TOP + 0.17, 0.9, 0.22, [(idx, {})], size=8.5, color=acc, font=MONO, spacing=1.4)
        add_text(s, x + 0.22, TOP + 0.42, w - 0.7, 0.3, [(title, {})], size=13, color=LG5, bold=True)
        if icon:
            add_icon(s, icon, x + w - 0.52, TOP + 0.17, 0.3)
        add_text(s, x + 0.22, TOP + 0.78, w - 0.4, NH - 0.9, [(cap, {})], size=9.5, color=G4, line_spacing=1.12)
    # the four stages inside the job node
    jx, jw = nodes[2][0], nodes[2][1]
    st = [("01", "Ingest", TURQ), ("02", "Extract", CERULEAN), ("03", "Audit · gate", TURQ), ("04", "Render", TURQ)]
    sgap = 0.1
    sw = (jw - 0.44 - 3 * sgap) / 4
    sy = TOP + NH - 0.62
    for i, (idx, name, acc) in enumerate(st):
        x = jx + 0.22 + i * (sw + sgap)
        add_rect(s, x, sy, sw, 0.42, fill=DG2, line=(CERULEAN_DIM if acc == CERULEAN else DG4), radius=0.12)
        add_text(s, x, sy + 0.06, sw, 0.15, [(idx, {})], size=7.5, color=acc, font=MONO, align=PP_ALIGN.CENTER)
        add_text(s, x, sy + 0.2, sw, 0.2, [(name, {})], size=8.5, color=(LG5 if acc == CERULEAN else G5),
                 bold=(acc == CERULEAN), align=PP_ALIGN.CENTER)
        if i < 3:
            add_line(s, x + sw + 0.01, sy + 0.21, x + sw + sgap - 0.01, sy + 0.21, color=G1, width=0.75, head=True)
    # connectors between nodes
    mid = TOP + 0.55
    for i in range(4):
        add_line(s, nodes[i][0] + nodes[i][1] + 0.02, mid, nodes[i + 1][0] - 0.02, mid, color=G2, width=1.0, head=True)
    # the human return loop
    ly = TOP + NH + 0.2
    hx, sx = nodes[3][0] + 0.6, nodes[0][0] + 0.6
    add_line(s, hx, TOP + NH, hx, ly, color=GOLD_DIM, width=1.0, dash="dash")
    add_line(s, hx, ly, sx, ly, color=GOLD_DIM, width=1.0, dash="dash")
    add_line(s, sx, ly, sx, TOP + NH + 0.02, color=GOLD_DIM, width=1.0, dash="dash", head=True)
    add_text(s, 2.3, ly + 0.05, 7.2, 0.22,
             [("the reviewer uploads the approved STTM  →  the next sync pairs it  →  it becomes a template", {})],
             size=8, color=GOLD, font=MONO, align=PP_ALIGN.CENTER)

    # ----- band 2: images ----------------------------------------------------------
    IY, IH = 4.45, 1.9
    frames = [  # x, w, image, tag, title, caption, accent
        (0.6, 2.85, frd_img, "in", "the FRD",
         "strict fields — paths, patterns, tables — must appear verbatim; underlined is what 03 checks", CERULEAN),
        (3.65, 2.85, pick, "app", "pick an FRD",
         "the corpus the sync landed: unmapped FRDs get Generate, mapped ones show their approved STTM", TURQ),
        (6.7, 2.85, review, "app", "resolve what the agent could not",
         "gated questions answered in place; re-render is stage 04 only — nothing re-extracted or billed", GOLD),
        (9.75, 3.0, wb_img, "out", "the STTM",
         "client dialect, one sheet per table; the FRD rule sits in the Comment cell of the row it names", TURQ),
    ]
    for x, w, img, tag, title, cap, acc in frames:
        add_rect(s, x, IY, w, IH, fill=DG1, line=DG4, radius=0.03)
        add_rect(s, x + 0.1, IY + 0.1, w - 0.2, IH - 0.62, fill=DG2, line=DG3, radius=0.02)
        if img:
            add_image(s, img, x + 0.12, IY + 0.12, w - 0.24, IH - 0.66)
        add_dot(s, x + 0.2, IY + IH - 0.36, 0.08, acc)
        add_text(s, x + 0.33, IY + IH - 0.45, w - 0.45, 0.22,
                 [(title, {"color": LG5, "bold": True, "size": 9.5}),
                  (f"   {tag}", {"color": G2, "font": MONO, "size": 7.5})], size=9.5)
        add_text(s, x + 0.33, IY + IH - 0.24, w - 0.45, 0.22, [(cap, {})], size=7.5, color=G3)

    # ----- footer --------------------------------------------------------------------
    FY = 6.62
    add_line(s, 0.6, FY, W_IN - 0.6, FY, color=DG4, width=0.5)
    add_text(s, 0.6, FY + 0.12, 8.5, 0.3,
             [("the model proposes", {"color": CERULEAN, "bold": True}), ("     ·     ", {"color": DG5}),
              ("deterministic code audits and decides", {"color": TURQ, "bold": True}), ("     ·     ", {"color": DG5}),
              ("a person resolves", {"color": GOLD, "bold": True})], size=11)
    add_text(s, 0.6, FY + 0.42, 9.5, 0.25,
             [("Grounding checks, gate status, pairing verdicts, template choice and eval scores are computed in code — "
               "never by the model. Fail loud: no silent mock, no silent live, no stale copies.", {})], size=8.5, color=G4)
    add_text(s, W_IN - 4.6, FY + 0.17, 4.0, 0.2,
             [("staging · 2026-08-22 · verified offline · live deploy pending", {})], size=7.5, color=G1, font=MONO,
             align=PP_ALIGN.RIGHT)

    out.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(out))
    return out


if __name__ == "__main__":
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT_DEFAULT
    print(build(target))
