"""Build the FRD-to-STTM one-slide system-architecture deck (PPTX).

    .venv/bin/pip install python-pptx pillow     # deck-building only, not runtime deps
    .venv/bin/python scripts/build_architecture_onepager.py [output.pptx]

Default output: context/FRD_to_STTM_Agent_System_Architecture.pptx

ONE slide — "Signal" theme, LIGHT variant since v4 (white canvas, Arjun 2026-08-22;
the dark v3 palette is recorded in ONEPAGER_DESIGN.md) — design philosophy + theme spec in
scripts/deck_assets/ONEPAGER_DESIGN.md, written with the canvas-design,
algorithmic-art, brand-guidelines and theme-factory skills, 2026-08-22):

  header   title, one-line subtitle, three status chips
  flow     five nodes on one axis — SharePoint (with the FRD page as a
           thumbnail) → scheduled read-only sync → the four-stage Databricks
           job (stage 02, the ONLY model call, in Claude orange) → the review
           app (human) → outputs (with the STTM sheet as a thumbnail) — and
           the gold return loop (the reviewer uploads; the sync pairs it)
  footer   the doctrine line + a status tag

v3 (2026-08-22, after "too crowded / text unclear" feedback on v2): the
four-image strip under the flow was REMOVED (the screenshot in
screenshots/ marked it); the two document previews moved INTO the end
nodes as thumbnails; ≈110 words; body 11 pt near-white, titles 15 pt,
nothing under 9 pt; mono only for identifiers. Background is a seeded,
reproducible flow-field (algorithmic-art: "Field Dynamics") — particles
crossing left to right, calm where the nodes sit — generated by this
script with Pillow. Colour is a semantic code: Claude orange `d97757`
(Anthropic brand accent, brand-guidelines) = the single LLM call;
turquoise = deterministic code; gold = a person; indigo = external system.
Fonts: Calibri + Courier New (ship with Office; render true-to-width in
LibreOffice QA). Assets land in scripts/deck_assets/onepager_generated/;
Lucide icons in scripts/deck_assets/icons_dark (react-icons/lu).

Every statement on the slide is true of `staging` as of 2026-08-22; the
slide claims no live deployment.
"""
from __future__ import annotations

import math
import random
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_CONNECTOR, MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.oxml.ns import qn
from pptx.util import Inches, Pt

REPO = Path(__file__).resolve().parent.parent
ASSETS = REPO / "scripts" / "deck_assets"
ICONS = ASSETS / "icons_light"
GEN = ASSETS / "onepager_generated"
OUT_DEFAULT = REPO / "context" / "FRD_to_STTM_Agent_System_Architecture.pptx"

# --- Signal Light theme (see ONEPAGER_DESIGN.md; white canvas since v4) --------
# Each accent has a SHAPE shade (dots, borders, lines) and a DIM shade dark
# enough for text on white. Blueprint shades throughout, except Claude orange.
CANVAS = "ffffff"
CARD, RAISED, HAIR, HAIR2 = "f6f7f9", "edeff2", "d3d8de", "c5cbd3"
T_MUTED, T_SEC, T_PRI = "5f6b7c", "2f343c", "1c2127"
INK = "111418"
LLM, LLM_DIM, LLM_TINT = "d97757", "a04d2c", "fbeee8"   # Claude orange — the one model call
CODE, CODE_DIM = "00a396", "007067"                     # deterministic code
HUMAN, HUMAN_DIM = "d1980b", "866103"                   # a person
EXT, EXT_DIM = "7961db", "5642a6"                       # external system

SANS, MONO = "Calibri", "Consolas"   # Courier New renders too thin in PowerPoint (screenshot 2026-08-22 9:03 PM)
W_IN, H_IN = 13.333, 7.5
SEED = 20260822

_FONT_CANDIDATES = {
    "sans": ["/System/Library/Fonts/Helvetica.ttc", "/Library/Fonts/Arial.ttf",
             "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"],
    "mono": ["/System/Library/Fonts/Menlo.ttc", "/Library/Fonts/Courier New.ttf",
             "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"],
}


def _font(kind: str, size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    for p in _FONT_CANDIDATES[kind]:
        if Path(p).exists():
            try:
                return ImageFont.truetype(p, size, index=1 if (bold and p.endswith(".ttc")) else 0)
            except OSError:
                return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def _hex(h: str, a: int = 255):
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), a)


# --------------------------------------------------------------------------- #
# generated images
# --------------------------------------------------------------------------- #
def _value_noise(rng: random.Random, gw: int, gh: int):
    """Tiny seeded value-noise lattice + bilinear sampler — enough for a
    calm, layered vector field without a numpy/noise dependency."""
    grid = [[rng.random() for _ in range(gw + 1)] for _ in range(gh + 1)]

    def sample(u: float, v: float) -> float:
        u = max(0.0, min(gw - 1e-6, u))
        v = max(0.0, min(gh - 1e-6, v))
        i, j = int(u), int(v)
        fu, fv = u - i, v - j
        fu = fu * fu * (3 - 2 * fu)
        fv = fv * fv * (3 - 2 * fv)
        a = grid[j][i] * (1 - fu) + grid[j][i + 1] * fu
        b = grid[j + 1][i] * (1 - fu) + grid[j + 1][i + 1] * fu
        return a * (1 - fv) + b * fv

    return sample


def make_background(path: Path) -> Path:
    """Field Dynamics: seeded particles born on the left edge follow a
    layered-noise field left→right, leaving faint trails — dense at the two
    edges, calm in the middle band where the nodes sit."""
    w, h = 2560, 1440
    rng = random.Random(SEED)
    n1, n2 = _value_noise(rng, 9, 5), _value_noise(rng, 23, 13)
    base = Image.new("RGB", (w, h), "#" + CANVAS)
    glow = Image.new("RGB", (w, h), "#" + CANVAS)
    gd = ImageDraw.Draw(glow)
    gd.ellipse([-500, -600, 1400, 800], fill="#eef1f5")
    gd.ellipse([1700, 800, 3300, 2000], fill="#f1f3f6")
    glow = glow.filter(ImageFilter.GaussianBlur(280))
    base = Image.blend(base, glow, 0.9)

    trails = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    td = ImageDraw.Draw(trails)
    cols = [_hex(CODE), _hex(EXT), _hex("2d72d2"), _hex("8f99a8")]
    for k in range(2600):
        x = rng.uniform(-40, 120)
        y = rng.uniform(0, h)
        col = cols[k % len(cols)]
        pts = [(x, y)]
        for _ in range(rng.randint(60, 140)):
            a = (n1(x / w * 9, y / h * 5) - 0.5) * 2.2 + (n2(x / w * 23, y / h * 13) - 0.5) * 1.1
            ang = a * 1.4  # mostly rightward, gently curling
            x += math.cos(ang) * 9
            y += math.sin(ang) * 9
            if not (0 <= y < h) or x > w + 40:
                break
            pts.append((x, y))
        if len(pts) < 3:
            continue
        # the band where the nodes sit (≈ 24 %–58 % of height) is kept calm
        for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
            band = 0.24 * h <= y0 <= 0.58 * h
            edge = min(x0, w - x0) / (0.32 * w)
            alpha = 34 * max(0.0, min(1.0, 1.15 - edge))
            if band:
                alpha *= 0.22
            if alpha < 2:
                continue
            td.line([(x0, y0), (x1, y1)], fill=(col[0], col[1], col[2], int(alpha)), width=2)
    trails = trails.filter(ImageFilter.GaussianBlur(0.6))
    img = Image.alpha_composite(base.convert("RGBA"), trails).convert("RGB")
    d = ImageDraw.Draw(img)
    for yy in range(40, h, 40):
        for xx in range(40, w, 40):
            d.point((xx, yy), fill="#dfe3e8")
    img.save(path, optimize=True)
    return path


FRD_LINES = [  # the SYNTHETIC smoke FRD (tools/make_synthetic_smoke_fixture.py)
    ("h", "Functional Requirements Document"),
    ("m", "Project ID: 9100001   Project Name: Synthetic Member Risk Ingestion"),
    ("", ""),
    ("s", "Data Ingestion Requirements"),
    ("p", "The Synthetic Vendor delivers the pipe (|) delimited text file"),
    ("p", "{SYN_MEMBER_RISK_YYYYMMDD.txt} weekly to {/synthetic/landing/synthetic_member_risk}."),
    ("p", "The feed loads the columns MEMBER_ID, ZIP_CODE, RISK_SCORE, EFFECTIVE_DATE,"),
    ("p", "LOB_CODE into the stage table {syn_cat.syn_stg.SYN_MEMBER_RISK} (Truncate and"),
    ("p", "Load) and is promoted to {syn_cat.syn_std.SYN_MEMBER_RISK}."),
    ("", ""),
    ("s", "Data Quality"),
    ("p", "REQ-001  Process shall reject the record when MEMBER_ID is NULL and move"),
    ("p", "it to the reject table."),
]


def make_frd_preview(path: Path) -> Path:
    """Close-up of the synthetic FRD at thumbnail scale: the project line and
    ONE requirement in large type, the strict-grounded span underlined in
    Claude orange. (A whole page was illegible at 1.9 in — PowerPoint
    screenshots 2026-08-22 9:07 PM.)"""
    w, h = 1400, 720
    img = Image.new("RGB", (w, h), "#" + RAISED)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([24, 24, w - 24, h - 24], radius=22, fill="#ffffff", outline="#d3d8de", width=3)
    f_small, f_head, f_body, f_req = _font("mono", 44), _font("sans", 62, True), _font("sans", 66), _font("sans", 48, True)
    d.text((80, 70), "FRD  ·  Project ID 9100001", font=f_small, fill="#5f6b7c")
    d.text((80, 140), "Data Quality", font=f_head, fill="#215db0")
    d.rounded_rectangle([80, 250, 330, 318], radius=12, fill="#e8f0fb")
    d.text((104, 260), "REQ-001", font=f_req, fill="#215db0")
    lines = ["Process shall reject the record", "when {MEMBER_ID} is NULL and move", "it to the reject table."]
    y = 340
    for line in lines:
        x = 80
        for part in re.split(r"(\{[^}]+\})", line):
            if not part:
                continue
            strict = part.startswith("{")
            t = part.strip("{}")
            d.text((x, y), t, font=f_body, fill="#1c2127")
            tw = d.textlength(t, font=f_body)
            if strict:
                d.line([x, y + 78, x + tw, y + 78], fill="#" + LLM, width=8)
            x += tw
        y += 96
    img.save(path, optimize=True)
    return path


WB_ROWS = [  # synthetic smoke rows as 04 renders them (sheet MAPPING-SYN_MEMBER_RISK)
    ("MEMBER_ID", "Not NULL", "Process shall reject the record when MEMBER_ID is NULL…", "syn_stg", "SYN_MEMBER_RISK", "MEMBER_ID"),
    ("ZIP_CODE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "ZIP_CODE"),
    ("RISK_SCORE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "RISK_SCORE"),
    ("EFFECTIVE_DATE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "EFFECTIVE_DATE"),
    ("LOB_CODE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "LOB_CODE"),
    ("NA", "NULL", "", "syn_stg", "SYN_MEMBER_RISK", "SYN_SRC_FILE"),
    ("NA", "NULL", "", "syn_stg", "SYN_MEMBER_RISK", "SYN_LOAD_TS"),
]


def make_workbook_preview(path: Path) -> Path:
    """Close-up of the rendered STTM sheet at thumbnail scale — the Outputs
    node is the narrowest, so: three columns, three rows, large type; the
    Comment cell carries the FRD rule on the row it names."""
    w, h = 1400, 930
    img = Image.new("RGB", (w, h), "#" + RAISED)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([24, 24, w - 24, h - 24], radius=22, fill="#ffffff", outline="#d3d8de", width=3)
    f_tab, f_hd, f_cell, f_mono = _font("sans", 50), _font("sans", 66, True), _font("sans", 70), _font("mono", 64)
    d.rounded_rectangle([80, 70, 860, 150], radius=12, fill="#e8f0fb")
    d.text((100, 86), "MAPPING-SYN_MEMBER_RISK", font=f_tab, fill="#215db0")
    cols = [("Column", 470), ("Null", 300), ("Comment", 550)]
    x0, y0, hh, rh = 80, 200, 130, 210
    x = x0
    for name, cw in cols:
        d.rectangle([x, y0, x + cw, y0 + hh], fill="#d9e1f2", outline="#ffffff", width=3)
        d.text((x + 24, y0 + 28), name, font=f_hd, fill="#1c2127")
        x += cw
    rows = [("MEMBER_ID", "Not NULL", "reject if NULL"),
            ("ZIP_CODE", "Not NULL", "")]
    y = y0 + hh
    for r in rows:
        x = x0
        for (name, cw), val in zip(cols, r):
            d.rectangle([x, y, x + cw, y + rh], fill="#ffffff", outline="#e5e8eb", width=3)
            if name == "Comment" and val:
                d.rectangle([x + 3, y + 3, x + cw - 3, y + rh - 3], fill="#" + LLM_TINT)
                d.text((x + 24, y + 60), val, font=f_cell, fill="#" + LLM_DIM)
            else:
                d.text((x + 24, y + 62), val, font=(f_mono if name == "Column" else f_cell), fill="#1c2127")
            x += cw
        y += rh
    img.save(path, optimize=True)
    return path


# --------------------------------------------------------------------------- #
# pptx helpers
# --------------------------------------------------------------------------- #
def rgb(h: str) -> RGBColor:
    return RGBColor.from_string(h.upper())


def _no_shadow(shape):
    spPr = shape._element.spPr
    spPr.append(spPr.makeelement(qn("a:effectLst"), {}))


def add_text(slide, x, y, w, h, runs, *, size=11, color=T_SEC, font=SANS, bold=False,
             align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP, spacing=None, line_spacing=None):
    tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    tf.vertical_anchor = anchor
    paragraphs = runs
    if isinstance(runs, str):
        paragraphs = [[(runs, {})]]
    elif runs and not isinstance(runs[0], list):
        paragraphs = [runs]
    for pi, para in enumerate(paragraphs):
        p = tf.paragraphs[0] if pi == 0 else tf.add_paragraph()
        p.alignment = align
        if line_spacing:
            p.line_spacing = line_spacing
        for text, ov in para:
            r = p.add_run()
            r.text = text
            f = r.font
            f.name = ov.get("font", font)
            f.size = Pt(ov.get("size", size))
            f.bold = ov.get("bold", bold)
            f.color.rgb = rgb(ov.get("color", color))
            sp = ov.get("spacing", spacing)
            if sp is not None:
                r._r.get_or_add_rPr().set("spc", str(int(sp * 100)))
    return tb


def add_rect(slide, x, y, w, h, *, fill=CARD, line=HAIR, line_w=0.75, radius=None):
    kind = MSO_SHAPE.ROUNDED_RECTANGLE if radius is not None else MSO_SHAPE.RECTANGLE
    s = slide.shapes.add_shape(kind, Inches(x), Inches(y), Inches(w), Inches(h))
    if radius is not None:
        s.adjustments[0] = radius
    if fill is None:
        s.fill.background()
    else:
        s.fill.solid()
        s.fill.fore_color.rgb = rgb(fill)
    if line is None:
        s.line.fill.background()
    else:
        s.line.color.rgb = rgb(line)
        s.line.width = Pt(line_w)
    _no_shadow(s)
    s.text_frame.text = ""
    return s


def add_line(slide, x1, y1, x2, y2, *, color=HAIR2, width=0.75, head=False, dash=None):
    c = slide.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(x1), Inches(y1), Inches(x2), Inches(y2))
    c.line.color.rgb = rgb(color)
    c.line.width = Pt(width)
    ln = c.line._get_or_add_ln()
    if dash:
        ln.append(ln.makeelement(qn("a:prstDash"), {"val": dash}))
    if head:
        ln.append(ln.makeelement(qn("a:tailEnd"), {"type": "triangle", "w": "sm", "len": "sm"}))
    return c


def add_dot(slide, cx, cy, d, color):
    s = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(cx - d / 2), Inches(cy - d / 2), Inches(d), Inches(d))
    s.fill.solid()
    s.fill.fore_color.rgb = rgb(color)
    s.line.fill.background()
    _no_shadow(s)
    return s


def add_icon(slide, name, x, y, size):
    p = ICONS / f"{name}.png"
    if p.exists():
        slide.shapes.add_picture(str(p), Inches(x), Inches(y), Inches(size), Inches(size))


def add_image(slide, path, x, y, w, h):
    iw, ih = Image.open(path).size
    scale = min(w / iw, h / ih)
    pw, ph = iw * scale, ih * scale
    slide.shapes.add_picture(str(path), Inches(x + (w - pw) / 2), Inches(y + (h - ph) / 2), Inches(pw), Inches(ph))


CHIP_CHAR, CHIP_PAD = 0.086, 0.4    # Calibri Bold 8.5 pt caps + 1 pt tracking, measured in QA


def chip(slide, x, y, text, *, color=T_SEC, border=HAIR2, size=8.5):
    w = CHIP_CHAR * len(text) + CHIP_PAD
    add_rect(slide, x, y, w, 0.3, fill=None, line=border, line_w=1.0, radius=0.5)
    add_text(slide, x, y + 0.07, w, 0.2, [(text.upper(), {})], size=size, color=color, font=SANS, bold=True,
             spacing=1.0, align=PP_ALIGN.CENTER)
    return x + w + 0.12


def crosshair(slide, cx, cy, arm=0.07):
    add_line(slide, cx - arm, cy, cx + arm, cy, color=HAIR2, width=0.5)
    add_line(slide, cx, cy - arm, cx, cy + arm, color=HAIR2, width=0.5)


# --------------------------------------------------------------------------- #
# the slide
# --------------------------------------------------------------------------- #
def build(out: Path) -> Path:
    GEN.mkdir(parents=True, exist_ok=True)
    for stale in ("shot_pick.png", "shot_review.png"):   # v2 assets, no longer on the slide
        (GEN / stale).unlink(missing_ok=True)
    bg = make_background(GEN / "background.png")
    frd_img = make_frd_preview(GEN / "frd_page.png")
    wb_img = make_workbook_preview(GEN / "sttm_sheet.png")

    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(W_IN), Inches(H_IN)
    s = prs.slides.add_slide(prs.slide_layouts[6])
    s.shapes.add_picture(str(bg), 0, 0, prs.slide_width, prs.slide_height)
    for cx, cy in ((0.3, 0.3), (W_IN - 0.3, 0.3), (0.3, H_IN - 0.3), (W_IN - 0.3, H_IN - 0.3)):
        crosshair(s, cx, cy)

    # ----- header ------------------------------------------------------------
    add_text(s, 0.6, 0.46, 9, 0.24,
             [("HEXAWARE  ·  AMERIHEALTH CARITAS  ·  AI-IN-ENGINEERING  ·  AGENT 01 / 03", {})],
             size=9, color=T_MUTED, font=SANS, bold=True, spacing=1.4)
    add_text(s, 0.6, 0.72, 9.5, 0.6, [("FRD → STTM Agent", {"color": INK, "bold": True, "size": 30}),
                                      ("    system architecture", {"color": T_MUTED, "size": 16})], size=30)
    add_text(s, 0.6, 1.28, 12.1, 0.3,
             [("An approved requirements document becomes an audited source-to-target mapping — "
               "every fact checked against the source text, every ambiguity routed to a person.", {})],
             size=12, color=T_SEC)
    chips = [("pulls from SharePoint · never writes back", EXT_DIM, EXT), ("1 model call per document", LLM_DIM, LLM),
             ("verdicts computed in code", CODE_DIM, CODE)]
    cx = 0.6
    for t, col, bd in chips:
        cx = chip(s, cx, 1.68, t, color=col, border=bd)

    # ----- the flow ------------------------------------------------------------
    TOP, NH = 2.2, 3.05
    nodes = [  # x, w, accent, icon, idx, title, caption, thumbnail
        (0.6, 2.05, EXT, "folder", "SRC", "SharePoint",
         "System of record. The sync pulls FRDs and STTMs into Databricks and never writes back.", frd_img),
        (2.95, 1.95, CODE, "refresh", "00", "Scheduled sync",
         "Every 15 minutes, incremental. Pairs each FRD with its STTM and indexes the corpus in Unity Catalog. Zero model calls.", None),
        (5.2, 2.8, CODE, None, "01–04", "Generation job",
         "Four stages on Databricks. Extract is the single Claude call; parsing, grounding audit, gate and render are code.", None),
        (8.3, 1.85, HUMAN, "user", "HITL", "Review app",
         "Pick an FRD, run, answer what the agent could not settle, re-render — then upload the approved STTM yourself.", None),
        (10.45, 2.28, EXT, "code", "OUT", "Outputs",
         "STTM workbook + feed contract → CodeGen and Code Review agents.", wb_img),
    ]
    DIM = {LLM: LLM_DIM, CODE: CODE_DIM, HUMAN: HUMAN_DIM, EXT: EXT_DIM}
    for x, w, acc, icon, idx, title, cap, thumb in nodes:
        add_rect(s, x, TOP, w, NH, fill=CARD, line=HAIR, radius=0.035)
        add_dot(s, x + 0.26, TOP + 0.3, 0.11, acc)
        add_text(s, x + 0.44, TOP + 0.19, 1.0, 0.24, [(idx, {})], size=9, color=DIM[acc], font=MONO, bold=True, spacing=1.2)
        add_text(s, x + 0.24, TOP + 0.46, w - 0.4, 0.34, [(title, {})], size=14.5, color=T_PRI, bold=True)
        if icon:
            add_icon(s, icon, x + w - 0.52, TOP + 0.16, 0.3)
        add_text(s, x + 0.24, TOP + 0.88, w - 0.46, 1.2, [(cap, {})], size=11, color=T_SEC, line_spacing=1.12)
        if thumb is not None:
            th = 0.88
            add_rect(s, x + 0.16, TOP + NH - th - 0.16, w - 0.32, th, fill=RAISED, line=HAIR2, radius=0.03)
            add_image(s, thumb, x + 0.18, TOP + NH - th - 0.14, w - 0.36, th - 0.04)

    # stage chips inside the job node
    jx, jw = nodes[2][0], nodes[2][1]
    st = [("01", "Ingest", CODE), ("02", "Extract", LLM), ("03", "Audit", CODE), ("04", "Render", CODE)]
    sgap = 0.1
    sw = (jw - 0.48 - 3 * sgap) / 4
    sy = TOP + NH - 0.98
    for i, (idx, name, acc) in enumerate(st):
        x = jx + 0.24 + i * (sw + sgap)
        is_llm = acc == LLM
        add_rect(s, x, sy, sw, 0.5, fill=(LLM_TINT if is_llm else RAISED), line=(LLM if is_llm else HAIR2),
                 line_w=(1.25 if is_llm else 0.75), radius=0.1)
        add_text(s, x, sy + 0.07, sw, 0.18, [(idx, {})], size=8.5, color=(LLM_DIM if is_llm else CODE_DIM), font=MONO,
                 bold=True, align=PP_ALIGN.CENTER)
        add_text(s, x, sy + 0.24, sw, 0.22, [(name, {})], size=9, color=(LLM_DIM if is_llm else T_PRI), bold=is_llm,
                 align=PP_ALIGN.CENTER)
        if i < 3:
            add_line(s, x + sw + 0.01, sy + 0.25, x + sw + sgap - 0.01, sy + 0.25, color=HAIR2, width=0.75, head=True)
    add_text(s, jx + 0.24, sy + 0.6, jw - 0.48, 0.24,
             [("02 is the only model call", {})], size=9.5, color=LLM_DIM,
             align=PP_ALIGN.CENTER)

    # connectors between nodes
    mid = TOP + 0.6
    for i in range(4):
        add_line(s, nodes[i][0] + nodes[i][1] + 0.02, mid, nodes[i + 1][0] - 0.02, mid, color=T_SEC, width=1.25, head=True)

    # the human return loop
    ly = TOP + NH + 0.26
    hx, sx = nodes[3][0] + 0.7, nodes[0][0] + 0.7
    add_line(s, hx, TOP + NH, hx, ly, color=HUMAN, width=1.25, dash="dash")
    add_line(s, hx, ly, sx, ly, color=HUMAN, width=1.25, dash="dash")
    add_line(s, sx, ly, sx, TOP + NH + 0.02, color=HUMAN, width=1.25, dash="dash", head=True)
    add_text(s, 1.2, ly + 0.08, 9.6, 0.26,
             [("the reviewer uploads the approved STTM   →   the next sync pairs it   →   it becomes a template", {})],
             size=9.5, color=HUMAN_DIM, font=SANS, bold=True, align=PP_ALIGN.CENTER)

    # ----- footer --------------------------------------------------------------
    FY = 6.3
    add_line(s, 0.6, FY, W_IN - 0.6, FY, color=HAIR, width=0.5)
    add_text(s, 0.6, FY + 0.14, 9.5, 0.34,
             [("the model proposes", {"color": LLM_DIM, "bold": True}), ("      ·      ", {"color": HAIR2}),
              ("deterministic code audits and decides", {"color": CODE_DIM, "bold": True}), ("      ·      ", {"color": HAIR2}),
              ("a person resolves", {"color": HUMAN_DIM, "bold": True})], size=12)
    add_text(s, 0.6, FY + 0.5, 12.1, 0.3,
             [("Grounding checks, gate status, pairing verdicts, template choice and eval scores are computed in code, "
               "never by the model. Fail loud — no silent mock, no silent live, no stale copies.", {})], size=10, color=T_SEC)
    add_text(s, W_IN - 5.4, FY + 0.2, 4.8, 0.22,
             [("staging · 2026-08-22 · verified offline · live deploy pending", {})], size=8.5, color=T_MUTED, font=SANS,
             align=PP_ALIGN.RIGHT)

    out.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(out))
    return out


if __name__ == "__main__":
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT_DEFAULT
    print(build(target))
