"""Build the FRD-to-STTM one-slide system-architecture deck (PPTX).

    .venv/bin/pip install python-pptx pillow     # deck-building only, not runtime deps
    .venv/bin/python scripts/build_architecture_onepager.py [output.pptx]

Default output: context/FRD_to_STTM_Agent_System_Architecture.pptx

ONE slide — "Signal Dark" (design philosophy + theme spec in
scripts/deck_assets/ONEPAGER_DESIGN.md, written with the canvas-design,
algorithmic-art, brand-guidelines and theme-factory skills, 2026-08-22):

  header   title, one-line subtitle, three status chips
  flow     five nodes on one axis — SharePoint (with the FRD page as a
           thumbnail) → scheduled read-only sync → the four-stage Databricks
           job (stage 02, the ONLY model call, in Claude orange) → the review
           app (human) → outputs (with the STTM sheet as a thumbnail) — and
           the gold return loop (the reviewer uploads; the sync pairs it)
  footer   the doctrine line + a status tag

v3 (2026-08-22, after "too crowded / text unclear" feedback on v2): the
four-image strip under the flow was REMOVED (the screenshot in
screenshots/ marked it); the two document previews moved INTO the end
nodes as thumbnails; ≈110 words; body 11 pt near-white, titles 15 pt,
nothing under 9 pt; mono only for identifiers. Background is a seeded,
reproducible flow-field (algorithmic-art: "Field Dynamics") — particles
crossing left to right, calm where the nodes sit — generated by this
script with Pillow. Colour is a semantic code: Claude orange `d97757`
(Anthropic brand accent, brand-guidelines) = the single LLM call;
turquoise = deterministic code; gold = a person; indigo = external system.
Fonts: Calibri + Courier New (ship with Office; render true-to-width in
LibreOffice QA). Assets land in scripts/deck_assets/onepager_generated/;
Lucide icons in scripts/deck_assets/icons_dark (react-icons/lu).

Every statement on the slide is true of `staging` as of 2026-08-22; the
slide claims no live deployment.
"""
from __future__ import annotations

import math
import random
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_CONNECTOR, MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.oxml.ns import qn
from pptx.util import Inches, Pt

REPO = Path(__file__).resolve().parent.parent
ASSETS = REPO / "scripts" / "deck_assets"
ICONS = ASSETS / "icons_dark"
GEN = ASSETS / "onepager_generated"
OUT_DEFAULT = REPO / "context" / "FRD_to_STTM_Agent_System_Architecture.pptx"

# --- Signal Dark theme (see ONEPAGER_DESIGN.md) ------------------------------
BLACK = "111418"
CARD, RAISED, HAIR, HAIR2 = "1c2127", "252a31", "383e47", "404854"
T_MUTED, T_SEC, T_PRI = "8f99a8", "c5cbd3", "f6f7f9"
WHITE = "ffffff"
LLM, LLM_DIM = "d97757", "8a4a36"        # Claude orange — the one model call
CODE, CODE_DIM = "13c9ba", "007067"      # deterministic code
HUMAN, HUMAN_DIM = "f0b726", "866103"    # a person
EXT, EXT_DIM = "9881f3", "634dbf"        # external system

SANS, MONO = "Calibri", "Courier New"
W_IN, H_IN = 13.333, 7.5
SEED = 20260822

_FONT_CANDIDATES = {
    "sans": ["/System/Library/Fonts/Helvetica.ttc", "/Library/Fonts/Arial.ttf",
             "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"],
    "mono": ["/System/Library/Fonts/Menlo.ttc", "/Library/Fonts/Courier New.ttf",
             "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"],
}


def _font(kind: str, size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    for p in _FONT_CANDIDATES[kind]:
        if Path(p).exists():
            try:
                return ImageFont.truetype(p, size, index=1 if (bold and p.endswith(".ttc")) else 0)
            except OSError:
                return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def _hex(h: str, a: int = 255):
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), a)


# --------------------------------------------------------------------------- #
# generated images
# --------------------------------------------------------------------------- #
def _value_noise(rng: random.Random, gw: int, gh: int):
    """Tiny seeded value-noise lattice + bilinear sampler — enough for a
    calm, layered vector field without a numpy/noise dependency."""
    grid = [[rng.random() for _ in range(gw + 1)] for _ in range(gh + 1)]

    def sample(u: float, v: float) -> float:
        u = max(0.0, min(gw - 1e-6, u))
        v = max(0.0, min(gh - 1e-6, v))
        i, j = int(u), int(v)
        fu, fv = u - i, v - j
        fu = fu * fu * (3 - 2 * fu)
        fv = fv * fv * (3 - 2 * fv)
        a = grid[j][i] * (1 - fu) + grid[j][i + 1] * fu
        b = grid[j + 1][i] * (1 - fu) + grid[j + 1][i + 1] * fu
        return a * (1 - fv) + b * fv

    return sample


def make_background(path: Path) -> Path:
    """Field Dynamics: seeded particles born on the left edge follow a
    layered-noise field left→right, leaving faint trails — dense at the two
    edges, calm in the middle band where the nodes sit."""
    w, h = 2560, 1440
    rng = random.Random(SEED)
    n1, n2 = _value_noise(rng, 9, 5), _value_noise(rng, 23, 13)
    base = Image.new("RGB", (w, h), "#" + BLACK)
    glow = Image.new("RGB", (w, h), "#" + BLACK)
    gd = ImageDraw.Draw(glow)
    gd.ellipse([-500, -600, 1400, 800], fill="#171d26")
    gd.ellipse([1700, 800, 3300, 2000], fill="#141a22")
    glow = glow.filter(ImageFilter.GaussianBlur(280))
    base = Image.blend(base, glow, 0.9)

    trails = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    td = ImageDraw.Draw(trails)
    cols = [_hex(CODE), _hex(EXT), _hex("4c90f0"), _hex(T_MUTED)]
    for k in range(2600):
        x = rng.uniform(-40, 120)
        y = rng.uniform(0, h)
        col = cols[k % len(cols)]
        pts = [(x, y)]
        for _ in range(rng.randint(60, 140)):
            a = (n1(x / w * 9, y / h * 5) - 0.5) * 2.2 + (n2(x / w * 23, y / h * 13) - 0.5) * 1.1
            ang = a * 1.4  # mostly rightward, gently curling
            x += math.cos(ang) * 9
            y += math.sin(ang) * 9
            if not (0 <= y < h) or x > w + 40:
                break
            pts.append((x, y))
        if len(pts) < 3:
            continue
        # the band where the nodes sit (≈ 24 %–58 % of height) is kept calm
        for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
            band = 0.24 * h <= y0 <= 0.58 * h
            edge = min(x0, w - x0) / (0.32 * w)
            alpha = 26 * max(0.0, min(1.0, 1.15 - edge))
            if band:
                alpha *= 0.22
            if alpha < 2:
                continue
            td.line([(x0, y0), (x1, y1)], fill=(col[0], col[1], col[2], int(alpha)), width=2)
    trails = trails.filter(ImageFilter.GaussianBlur(0.6))
    img = Image.alpha_composite(base.convert("RGBA"), trails).convert("RGB")
    d = ImageDraw.Draw(img)
    for yy in range(40, h, 40):
        for xx in range(40, w, 40):
            d.point((xx, yy), fill="#242a33")
    img.save(path, optimize=True)
    return path


FRD_LINES = [  # the SYNTHETIC smoke FRD (tools/make_synthetic_smoke_fixture.py)
    ("h", "Functional Requirements Document"),
    ("m", "Project ID: 9100001   Project Name: Synthetic Member Risk Ingestion"),
    ("", ""),
    ("s", "Data Ingestion Requirements"),
    ("p", "The Synthetic Vendor delivers the pipe (|) delimited text file"),
    ("p", "{SYN_MEMBER_RISK_YYYYMMDD.txt} weekly to {/synthetic/landing/synthetic_member_risk}."),
    ("p", "The feed loads the columns MEMBER_ID, ZIP_CODE, RISK_SCORE, EFFECTIVE_DATE,"),
    ("p", "LOB_CODE into the stage table {syn_cat.syn_stg.SYN_MEMBER_RISK} (Truncate and"),
    ("p", "Load) and is promoted to {syn_cat.syn_std.SYN_MEMBER_RISK}."),
    ("", ""),
    ("s", "Data Quality"),
    ("p", "REQ-001  Process shall reject the record when MEMBER_ID is NULL and move"),
    ("p", "it to the reject table."),
]


def make_frd_preview(path: Path) -> Path:
    """A page of the synthetic FRD; strict-grounded spans ({…}) underlined in
    Claude orange — the fields 03 must find verbatim."""
    w, h = 1400, 900
    img = Image.new("RGB", (w, h), "#" + RAISED)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([40, 30, w - 40, h + 40], radius=16, fill="#f6f7f9")
    fh, fs, fp, fm = _font("sans", 46, True), _font("sans", 32, True), _font("sans", 30), _font("mono", 25)
    y = 80
    for kind, text in FRD_LINES:
        x = 100
        if kind == "h":
            d.text((x, y), text, font=fh, fill="#1c2127"); y += 74
        elif kind == "m":
            d.text((x, y), text, font=fm, fill="#5f6b7c"); y += 60
        elif kind == "s":
            d.text((x, y), text, font=fs, fill="#215db0"); y += 56
        elif kind == "p":
            for part in re.split(r"(\{[^}]+\})", text):
                if not part:
                    continue
                strict = part.startswith("{")
                t = part.strip("{}")
                d.text((x, y), t, font=fp, fill="#1c2127")
                tw = d.textlength(t, font=fp)
                if strict:
                    d.line([x, y + 38, x + tw, y + 38], fill="#" + LLM, width=4)
                x += tw
            y += 46
        else:
            y += 26
    fade = Image.new("L", (w, h), 0)
    fd = ImageDraw.Draw(fade)
    for i in range(160):
        fd.line([0, h - 160 + i, w, h - 160 + i], fill=int(255 * i / 160))
    img = Image.composite(Image.new("RGB", (w, h), "#" + RAISED), img, fade)
    img.save(path, optimize=True)
    return path


WB_ROWS = [  # synthetic smoke rows as 04 renders them (sheet MAPPING-SYN_MEMBER_RISK)
    ("MEMBER_ID", "Not NULL", "Process shall reject the record when MEMBER_ID is NULL…", "syn_stg", "SYN_MEMBER_RISK", "MEMBER_ID"),
    ("ZIP_CODE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "ZIP_CODE"),
    ("RISK_SCORE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "RISK_SCORE"),
    ("EFFECTIVE_DATE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "EFFECTIVE_DATE"),
    ("LOB_CODE", "Not NULL", "", "syn_stg", "SYN_MEMBER_RISK", "LOB_CODE"),
    ("NA", "NULL", "", "syn_stg", "SYN_MEMBER_RISK", "SYN_SRC_FILE"),
    ("NA", "NULL", "", "syn_stg", "SYN_MEMBER_RISK", "SYN_LOAD_TS"),
]


def make_workbook_preview(path: Path) -> Path:
    """The rendered STTM sheet: band row, header row, rows — the Comment
    cell carries the FRD rule on the row it names."""
    w, h = 1400, 900
    img = Image.new("RGB", (w, h), "#" + RAISED)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([40, 30, w + 200, h + 40], radius=16, fill="#ffffff")
    ft = _font("sans", 24)
    tx = 70
    for name, active in (("FILE_DETAILS", False), ("VERSION_HISTORY", False), ("MAPPING-SYN_MEMBER_RISK", True)):
        tw = d.textlength(name, font=ft) + 40
        d.rounded_rectangle([tx, 48, tx + tw, 96], radius=8, fill=("#ffffff" if active else "#e5e8eb"), outline="#c5cbd3")
        d.text((tx + 20, 59), name, font=ft, fill=("#215db0" if active else "#5f6b7c"))
        tx += tw + 8
    cols = [("Database column Name", 270), ("NULL CHECK", 150), ("Comment", 520), ("Schema", 130),
            ("TableName", 250), ("ColumnName", 220)]
    x0, y0 = 40, 118
    fb, fhd, fc, fcm = _font("sans", 26, True), _font("sans", 25, True), _font("sans", 25), _font("mono", 23)
    x, ci = x0, 0
    for name, n in (("Source File Layout", 3), ("Stage Layer", 3)):
        bw = sum(cw for _, cw in cols[ci:ci + n])
        d.rectangle([x, y0, x + bw, y0 + 50], fill="#bdd7ee", outline="#ffffff")
        d.text((x + 14, y0 + 10), name, font=fb, fill="#1c2127")
        x += bw
        ci += n
    x = x0
    for name, cw in cols:
        d.rectangle([x, y0 + 50, x + cw, y0 + 100], fill="#d9e1f2", outline="#ffffff")
        d.text((x + 14, y0 + 61), name, font=fhd, fill="#1c2127")
        x += cw
    y = y0 + 100
    for r in WB_ROWS:
        x = x0
        for (name, cw), val in zip(cols, r):
            d.rectangle([x, y, x + cw, y + 54], fill="#ffffff", outline="#edeff2")
            if name == "Comment" and val:
                d.rectangle([x + 1, y + 1, x + cw - 1, y + 53], fill="#fbeee8")
                d.text((x + 14, y + 14), val, font=fcm, fill="#8a4a36")
            else:
                d.text((x + 14, y + 13), val,
                       font=(fcm if name in ("Schema", "TableName", "ColumnName") else fc),
                       fill=("#8f99a8" if val in ("NA", "NULL") else "#1c2127"))
            x += cw
        y += 54
    fade = Image.new("L", (w, h), 0)
    fd = ImageDraw.Draw(fade)
    for i in range(140):
        fd.line([w - 140 + i, 0, w - 140 + i, h], fill=int(255 * i / 140))
    img = Image.composite(Image.new("RGB", (w, h), "#" + RAISED), img, fade)
    img.save(path, optimize=True)
    return path


# --------------------------------------------------------------------------- #
# pptx helpers
# --------------------------------------------------------------------------- #
def rgb(h: str) -> RGBColor:
    return RGBColor.from_string(h.upper())


def _no_shadow(shape):
    spPr = shape._element.spPr
    spPr.append(spPr.makeelement(qn("a:effectLst"), {}))


def add_text(slide, x, y, w, h, runs, *, size=11, color=T_SEC, font=SANS, bold=False,
             align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP, spacing=None, line_spacing=None):
    tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    tf.vertical_anchor = anchor
    paragraphs = runs
    if isinstance(runs, str):
        paragraphs = [[(runs, {})]]
    elif runs and not isinstance(runs[0], list):
        paragraphs = [runs]
    for pi, para in enumerate(paragraphs):
        p = tf.paragraphs[0] if pi == 0 else tf.add_paragraph()
        p.alignment = align
        if line_spacing:
            p.line_spacing = line_spacing
        for text, ov in para:
            r = p.add_run()
            r.text = text
            f = r.font
            f.name = ov.get("font", font)
            f.size = Pt(ov.get("size", size))
            f.bold = ov.get("bold", bold)
            f.color.rgb = rgb(ov.get("color", color))
            sp = ov.get("spacing", spacing)
            if sp is not None:
                r._r.get_or_add_rPr().set("spc", str(int(sp * 100)))
    return tb


def add_rect(slide, x, y, w, h, *, fill=CARD, line=HAIR, line_w=0.75, radius=None):
    kind = MSO_SHAPE.ROUNDED_RECTANGLE if radius is not None else MSO_SHAPE.RECTANGLE
    s = slide.shapes.add_shape(kind, Inches(x), Inches(y), Inches(w), Inches(h))
    if radius is not None:
        s.adjustments[0] = radius
    if fill is None:
        s.fill.background()
    else:
        s.fill.solid()
        s.fill.fore_color.rgb = rgb(fill)
    if line is None:
        s.line.fill.background()
    else:
        s.line.color.rgb = rgb(line)
        s.line.width = Pt(line_w)
    _no_shadow(s)
    s.text_frame.text = ""
    return s


def add_line(slide, x1, y1, x2, y2, *, color=HAIR2, width=0.75, head=False, dash=None):
    c = slide.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(x1), Inches(y1), Inches(x2), Inches(y2))
    c.line.color.rgb = rgb(color)
    c.line.width = Pt(width)
    ln = c.line._get_or_add_ln()
    if dash:
        ln.append(ln.makeelement(qn("a:prstDash"), {"val": dash}))
    if head:
        ln.append(ln.makeelement(qn("a:tailEnd"), {"type": "triangle", "w": "sm", "len": "sm"}))
    return c


def add_dot(slide, cx, cy, d, color):
    s = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(cx - d / 2), Inches(cy - d / 2), Inches(d), Inches(d))
    s.fill.solid()
    s.fill.fore_color.rgb = rgb(color)
    s.line.fill.background()
    _no_shadow(s)
    return s


def add_icon(slide, name, x, y, size):
    p = ICONS / f"{name}.png"
    if p.exists():
        slide.shapes.add_picture(str(p), Inches(x), Inches(y), Inches(size), Inches(size))


def add_image(slide, path, x, y, w, h):
    iw, ih = Image.open(path).size
    scale = min(w / iw, h / ih)
    pw, ph = iw * scale, ih * scale
    slide.shapes.add_picture(str(path), Inches(x + (w - pw) / 2), Inches(y + (h - ph) / 2), Inches(pw), Inches(ph))


CHIP_CHAR, CHIP_PAD = 0.092, 0.36   # Courier New 8.5 pt + tracking, measured in QA


def chip(slide, x, y, text, *, color=T_SEC, border=HAIR2, size=8.5):
    w = CHIP_CHAR * len(text) + CHIP_PAD
    add_rect(slide, x, y, w, 0.3, fill=None, line=border, line_w=0.75, radius=0.5)
    add_text(slide, x, y + 0.07, w, 0.2, [(text.upper(), {})], size=size, color=color, font=MONO,
             spacing=1.0, align=PP_ALIGN.CENTER)
    return x + w + 0.12


def crosshair(slide, cx, cy, arm=0.07):
    add_line(slide, cx - arm, cy, cx + arm, cy, color=HAIR2, width=0.5)
    add_line(slide, cx, cy - arm, cx, cy + arm, color=HAIR2, width=0.5)


# --------------------------------------------------------------------------- #
# the slide
# --------------------------------------------------------------------------- #
def build(out: Path) -> Path:
    GEN.mkdir(parents=True, exist_ok=True)
    for stale in ("shot_pick.png", "shot_review.png"):   # v2 assets, no longer on the slide
        (GEN / stale).unlink(missing_ok=True)
    bg = make_background(GEN / "background.png")
    frd_img = make_frd_preview(GEN / "frd_page.png")
    wb_img = make_workbook_preview(GEN / "sttm_sheet.png")

    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(W_IN), Inches(H_IN)
    s = prs.slides.add_slide(prs.slide_layouts[6])
    s.shapes.add_picture(str(bg), 0, 0, prs.slide_width, prs.slide_height)
    for cx, cy in ((0.3, 0.3), (W_IN - 0.3, 0.3), (0.3, H_IN - 0.3), (W_IN - 0.3, H_IN - 0.3)):
        crosshair(s, cx, cy)

    # ----- header ------------------------------------------------------------
    add_text(s, 0.6, 0.46, 9, 0.24,
             [("HEXAWARE  ·  AMERIHEALTH CARITAS  ·  AI-IN-ENGINEERING  ·  AGENT 01 / 03", {})],
             size=9, color=T_MUTED, font=MONO, spacing=1.6)
    add_text(s, 0.6, 0.72, 9.5, 0.6, [("FRD → STTM Agent", {"color": WHITE, "bold": True, "size": 30}),
                                      ("    system architecture", {"color": T_MUTED, "size": 16})], size=30)
    add_text(s, 0.6, 1.28, 12.1, 0.3,
             [("An approved requirements document becomes an audited source-to-target mapping — "
               "every fact checked against the source text, every ambiguity routed to a person.", {})],
             size=12, color=T_SEC)
    chips = [("read-only SharePoint", EXT, EXT_DIM), ("1 model call per document", LLM, LLM_DIM),
             ("verdicts computed in code", CODE, CODE_DIM)]
    cx = 0.6
    for t, col, bd in chips:
        cx = chip(s, cx, 1.68, t, color=col, border=bd)

    # ----- the flow ------------------------------------------------------------
    TOP, NH = 2.2, 3.05
    nodes = [  # x, w, accent, icon, idx, title, caption, thumbnail
        (0.6, 2.2, EXT, "folder", "SRC", "SharePoint",
         "System of record. FRDs in, approved STTMs back. The agent only ever reads it.", frd_img),
        (3.1, 2.05, CODE, "refresh", "00", "Scheduled sync",
         "Every 15 minutes, incremental. Pairs each FRD with its STTM and indexes the corpus in Unity Catalog. Zero model calls.", None),
        (5.45, 2.95, CODE, None, "01–04", "Generation job",
         "Four stages on Databricks. Extract is the single Claude call; parsing, grounding audit, gate and render are code.", None),
        (8.7, 1.95, HUMAN, "user", "HITL", "Review app",
         "Pick an FRD, run, answer what the agent could not settle, re-render — then upload the approved STTM yourself.", None),
        (10.95, 1.78, EXT, "code", "OUT", "Outputs",
         "STTM workbook + feed contract → CodeGen and Code Review agents.", wb_img),
    ]
    for x, w, acc, icon, idx, title, cap, thumb in nodes:
        add_rect(s, x, TOP, w, NH, fill=CARD, line=HAIR, radius=0.035)
        add_dot(s, x + 0.26, TOP + 0.3, 0.11, acc)
        add_text(s, x + 0.44, TOP + 0.19, 1.0, 0.24, [(idx, {})], size=9, color=acc, font=MONO, spacing=1.4)
        add_text(s, x + 0.24, TOP + 0.46, w - 0.4, 0.34, [(title, {})], size=14.5, color=T_PRI, bold=True)
        if icon:
            add_icon(s, icon, x + w - 0.52, TOP + 0.16, 0.3)
        add_text(s, x + 0.24, TOP + 0.88, w - 0.46, 1.2, [(cap, {})], size=11, color=T_SEC, line_spacing=1.12)
        if thumb is not None:
            th = 0.98
            add_rect(s, x + 0.16, TOP + NH - th - 0.16, w - 0.32, th, fill=RAISED, line=HAIR2, radius=0.03)
            add_image(s, thumb, x + 0.18, TOP + NH - th - 0.14, w - 0.36, th - 0.04)

    # stage chips inside the job node
    jx, jw = nodes[2][0], nodes[2][1]
    st = [("01", "Ingest", CODE), ("02", "Extract", LLM), ("03", "Audit", CODE), ("04", "Render", CODE)]
    sgap = 0.1
    sw = (jw - 0.48 - 3 * sgap) / 4
    sy = TOP + NH - 0.98
    for i, (idx, name, acc) in enumerate(st):
        x = jx + 0.24 + i * (sw + sgap)
        is_llm = acc == LLM
        add_rect(s, x, sy, sw, 0.5, fill=(LLM_DIM if is_llm else RAISED), line=(LLM if is_llm else HAIR2),
                 line_w=(1.0 if is_llm else 0.75), radius=0.1)
        add_text(s, x, sy + 0.07, sw, 0.18, [(idx, {})], size=8.5, color=(T_PRI if is_llm else acc), font=MONO,
                 align=PP_ALIGN.CENTER)
        add_text(s, x, sy + 0.24, sw, 0.22, [(name, {})], size=9.5, color=T_PRI, bold=is_llm, align=PP_ALIGN.CENTER)
        if i < 3:
            add_line(s, x + sw + 0.01, sy + 0.25, x + sw + sgap - 0.01, sy + 0.25, color=HAIR2, width=0.75, head=True)
    add_text(s, jx + 0.24, sy + 0.6, jw - 0.48, 0.24,
             [("02 is the only model call", {})], size=9.5, color=LLM,
             align=PP_ALIGN.CENTER)

    # connectors between nodes
    mid = TOP + 0.6
    for i in range(4):
        add_line(s, nodes[i][0] + nodes[i][1] + 0.02, mid, nodes[i + 1][0] - 0.02, mid, color=T_MUTED, width=1.0, head=True)

    # the human return loop
    ly = TOP + NH + 0.26
    hx, sx = nodes[3][0] + 0.7, nodes[0][0] + 0.7
    add_line(s, hx, TOP + NH, hx, ly, color=HUMAN_DIM, width=1.25, dash="dash")
    add_line(s, hx, ly, sx, ly, color=HUMAN_DIM, width=1.25, dash="dash")
    add_line(s, sx, ly, sx, TOP + NH + 0.02, color=HUMAN_DIM, width=1.25, dash="dash", head=True)
    add_text(s, 1.2, ly + 0.08, 9.6, 0.26,
             [("the reviewer uploads the approved STTM   →   the next sync pairs it   →   it becomes a template", {})],
             size=9, color=HUMAN, font=MONO, align=PP_ALIGN.CENTER)

    # ----- footer --------------------------------------------------------------
    FY = 6.3
    add_line(s, 0.6, FY, W_IN - 0.6, FY, color=HAIR, width=0.5)
    add_text(s, 0.6, FY + 0.14, 9.5, 0.34,
             [("the model proposes", {"color": LLM, "bold": True}), ("      ·      ", {"color": HAIR2}),
              ("deterministic code audits and decides", {"color": CODE, "bold": True}), ("      ·      ", {"color": HAIR2}),
              ("a person resolves", {"color": HUMAN, "bold": True})], size=12)
    add_text(s, 0.6, FY + 0.5, 12.1, 0.3,
             [("Grounding checks, gate status, pairing verdicts, template choice and eval scores are computed in code, "
               "never by the model. Fail loud — no silent mock, no silent live, no stale copies.", {})], size=10, color=T_SEC)
    add_text(s, W_IN - 5.4, FY + 0.2, 4.8, 0.22,
             [("staging · 2026-08-22 · verified offline · live deploy pending", {})], size=8.5, color=T_MUTED, font=MONO,
             align=PP_ALIGN.RIGHT)

    out.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(out))
    return out


if __name__ == "__main__":
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT_DEFAULT
    print(build(target))
